CREATE DATABASE IshavantaOneCallServiceDb;
GO
USE IshavantaOneCallServiceDb;
GO
CREATE TABLE Services (Id INT PRIMARY KEY IDENTITY(1,1), Name NVARCHAR(120) NOT NULL, Description NVARCHAR(500) NULL, IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Portfolios (Id INT PRIMARY KEY IDENTITY(1,1), Title NVARCHAR(160) NOT NULL, Category NVARCHAR(80) NULL, Summary NVARCHAR(1000) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Blogs (Id INT PRIMARY KEY IDENTITY(1,1), Title NVARCHAR(160) NOT NULL, Slug NVARCHAR(160) NOT NULL, Content NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE ContactInquiries (Id INT PRIMARY KEY IDENTITY(1,1), Name NVARCHAR(120) NOT NULL, Email NVARCHAR(160) NOT NULL, Message NVARCHAR(MAX) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO


